### ISSUE TITLE
[question] What's wrong with Signal?

### ISSUE THREAD

**Issue by thiagodp** [ChALkeR/whinings#3]
I know that Signal is in your *to-do* list, but I'm just curious about your opinion on what's wrong with it.

**Comment by ChALkeR** [comment]
Hi! Entries on my to-do list are thost that I didn't take a cloer look on yet, and them being on my to-do list doesn't necessary mean that there is something wrong with those.

As for Signal specifically, the most obvious thing that is wrong is using mobile phone numbers as the primary identifiers (and those are linked to passport numbers in some countries, including the one I am in). Also, server-side is centralized (floss, though) — so it could be taken down (probably, need to take a closer look). Contacts list also appears to be leaking to the server.

I will look into it closer when I'll have time.

_Note: of everything listed there, GNU Ring looks like the closest thing to what I want to see on the first glance, after their recent (backwards-incompatible) update. But I also didn't have time to look closer on that one._

**Comment by thiagodp** [comment]
Hi! Great, @ChALkeR. Looking forward for the next items in the to-do. Thank you!
